Update create-releasev2.yml

diff --git a/.github/workflows/create-releasev2.yml b/.github/workflows/create-releasev2.yml
--- a/.github/workflows/create-releasev2.yml
+++ b/.github/workflows/create-releasev2.yml
@@ -1,13 +1,35 @@
-name: Release .NET Application AppA
+name: Release .NET Application
 
 on:
-  workflow_dispatch
+  workflow_dispatch:
+    inputs:
+      APP_NAME:
+        type: choice
+        options: 
+        - 'Please select an option...'
+        - 'AppA'
+        - 'AppB'
+        required: true
+        default: 'Please select an option...'
+        description: App to create a release for
 
 jobs:
+  validate-inputs:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Validate APP_NAME
+        run: |
+          if [[ "${{ inputs.APP_NAME }}" == "Please select an option..." ]]; then
+            echo "Error: You must select a valid application to release."
+            exit 1
+          fi
+          
   build-and-release:
+    needs: validate-inputs
     runs-on: ubuntu-latest
     env:
-      APP_PATH: 'src/Test/AppA/'
+      APP_PATH: 'src/Test/${{ inputs.APP_NAME }}/'
+      CORE_PATH: 'src/Test/Core/'
     steps:
     - uses: actions/checkout@v4
       with:
@@ -16,33 +38,31 @@ jobs:
     - name: Determine Changeset and Version Impact
       id: prep
       run: |
-        LAST_TAG=$(git tag --list 'appA*' --sort=-version:refname | head -n 1)
+        #LAST_TAG=$(git tag --list 'appA*' --sort=-version:refname | head -n 1)
+        LAST_TAG=$(git tag --list | grep -i '^${{ inputs.APP_NAME }}' | sort --version-sort --reverse | head -n 1)
         if [ -z "$LAST_TAG" ]; then
           LAST_TAG=$(git rev-list --max-parents=0 HEAD)
         fi
         echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV
         echo "Last tag: $LAST_TAG"
+       
+        CHANGED_FILES_APP=$(git diff --name-only $LAST_TAG HEAD | grep -E "$APP_PATH" || true)
+        CHANGED_FILES_CORE=$(git diff --name-only $LAST_TAG HEAD | grep -E "$CORE_PATH" || true)
+        echo "Changed Files in ${{ inputs.APP_NAME }}: $CHANGED_FILES_APP"
+        echo "Changed Files in Core: $CHANGED_FILES_CORE"
 
-        CHANGED_FILES=$(git diff --name-only $LAST_TAG HEAD | grep -E "$APP_PATH" || true)
-        echo "Changed Files: $CHANGED_FILES"
-        if [[ -z "$CHANGED_FILES" ]]; then
-          echo "APPA_AFFECTED=false"
-          echo "APPA_AFFECTED=false" >> $GITHUB_ENV
+        if [[ -z "$CHANGED_FILES_APP" && -z "$CHANGED_FILES_CORE" ]]; then
+          echo "APP_AFFECTED=false" >> $GITHUB_ENV
+          echo "No relevant changes detected. Skipping release."
           exit 1
         else
-          echo "APPA_AFFECTED=true"
-          echo "APPA_AFFECTED=true" >> $GITHUB_ENV
+          echo "APP_AFFECTED=true" >> $GITHUB_ENV
+          echo "Changes detected in ${{ inputs.APP_NAME }} or Core application. Preparing release."
         fi
 
         # Version calculation logic here, setting VERSION_CHANGED as needed
         # Enable case-insensitive matching
         shopt -s nocasematch
-
-        echo $LAST_TAG
-
-        if [[ $LAST_TAG != appA-v* ]]; then
-          echo "LAST_TAG=appA-v0.0.0" >> $GITHUB_ENV
-        fi
         
         # Initialize version components from the latest tag
         PREFIX=$(echo $LAST_TAG | grep -oE '^[^-]+-v')
@@ -56,30 +76,16 @@ jobs:
         MINOR_INC=0
         PATCH_INC=0
 
-        echo $LAST_TAG
-        # Check if the latest tag points to the initial commit (first release scenario)
-        if [[ $LAST_TAG == appA-v* ]]; then
-          echo "not first release"
-          # For subsequent releases, only consider commits since the latest tag
-          COMMIT_IDS=$(git log $LAST_TAG..HEAD --pretty=format:"%H" -- src/Test/AppA/)
-        else
-          # For the first release, consider all commits for AppA since the beginning of the repository
-          echo "First release"
-          COMMIT_IDS=$(git log --pretty=format:"%H" -- src/Test/AppA/)
-        fi
+        # Use git diff to analyze commits for version bump, filtering by appA and core directories
+        COMMIT_IDS=$(git log $LAST_TAG..HEAD --pretty=format:"%H" -- $APP_PATH $CORE_PATH)
 
-        # Use git diff to analyze commits for version bump, filtering by appA directory
-        #COMMIT_IDS=$(git log $LAST_TAG..HEAD --pretty=format:"%H")
-        
         for COMMIT_ID in $COMMIT_IDS
         do
-          # Check if the commit affects the appA directory
-          if git diff --name-only $COMMIT_ID^! | grep -q 'src/Test/AppA/'; then
-            #COMMIT_MSG=$(git log -1 --pretty=format:"%s" $COMMIT_ID)
+          if git diff --name-only $COMMIT_ID^! | grep -q -E "$APP_PATH|$CORE_PATH"; then
             COMMIT_MSG=$(git log -1 --pretty=format:"%s" $COMMIT_ID)
             if [[ "$COMMIT_MSG" =~ BREAKING[[:space:]]CHANGE: ]]; then
               MAJOR_INC=1
-              break # Stop processing further commits as major version increment is required
+              break # Major version increment is the highest, stop further analysis
             elif [[ "$COMMIT_MSG" =~ ^feat: ]]; then
               MINOR_INC=1
             elif [[ "$COMMIT_MSG" =~ ^fix: ]]; then
@@ -109,10 +115,8 @@ jobs:
         
         if [[ "$NEXT_VERSION" == "$LAST_TAG" ]]; then
           echo "VERSION_CHANGED=false" >> $GITHUB_ENV
-          echo "VERSION_CHANGED=false"
         else
           echo "VERSION_CHANGED=true" >> $GITHUB_ENV
-          echo "VERSION_CHANGED=true"
         fi
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
